### ISSUE TITLE
手滑插入过多文本框后如何移除?

### ISSUE THREAD

**Issue by b7woreo** [Huxpro/yanshuo.io#3]
没有找到类似`移除`的按钮, 只能 `ctrl+z` 撤销, 觉得应该加一个`移除`按钮

**Comment by Huxpro** [comment]
Delete 键可以删除，不过 ctrl+z 能保留焦点，不知道你指的移除是？

**Comment by b7woreo** [comment]
对对, 就是 Delete 那个功能, 只不过刚开始我以为会有一个 x 图标可以点击直接删掉或者在右键菜单里
